apiVersion: v1
kind: Service
metadata:
  name: cap-service
  namespace: mcp-cap-integration
  labels:
    app: cap-service
spec:
  selector:
    app: cap-service
  ports:
  - name: http
    protocol: TCP
    port: 4004
    targetPort: 4004
  type: ClusterIP
